version: '3.8'

services:
  gin-mcp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./resources:/app/resources
      - ./tools:/app/tools
    environment:
      - GIN_MCP_PORT=:8080
      - GIN_MCP_RESOURCES_DIR=/app/resources
      - GIN_MCP_TOOLS_DIR=/app/tools
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/mcp/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development version with debug mode
  gin-mcp-dev:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./resources:/app/resources
      - ./tools:/app/tools
      - .:/app/src  # Mount source for development
    environment:
      - GIN_MCP_PORT=:8080
      - GIN_MCP_RESOURCES_DIR=/app/resources
      - GIN_MCP_TOOLS_DIR=/app/tools
      - GIN_MODE=debug
    restart: unless-stopped
    profiles:
      - dev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/mcp/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 